<a href="https://colab.research.google.com/github/PabloMendieta/APRENDIZAJE_AUTOMATICO_23_24/blob/main/0%20INTRODUCCION/0.3.%20Vectores%20y%20matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lista = [5,6,9,8,7,4,65,2,2,56,46,54]
print(lista)

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]


In [2]:
2 in lista

True

In [3]:
35 in lista

False

In [4]:
lista[0]

5

In [5]:
lista[-1]

54

In [6]:
lista[2:4]

[9, 8]

In [7]:
lista[:5]

[5, 6, 9, 8, 7]

In [8]:
lista[4:]

[7, 4, 65, 2, 2, 56, 46, 54]

In [9]:
lista[:]

[5, 6, 9, 8, 7, 4, 65, 2, 2, 56, 46, 54]

In [10]:
import numpy as np

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [12]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
len(a)

4

In [14]:
min(a)

1

In [15]:
max(a)

4

In [16]:
b = np.array([[1,2,3],[5,6,4],[7,5,2]])
b

array([[1, 2, 3],
       [5, 6, 4],
       [7, 5, 2]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[:,1]

array([2, 6, 5])

In [19]:
b[2,2]

2

# Revisar la indexación de matrices (filas columnas)

In [20]:
b[0:2, 1:3]

array([[2, 3],
       [6, 4]])

In [21]:
a = np.random.rand(5,5)
a

array([[0.73188337, 0.41680205, 0.61963472, 0.31313189, 0.73430805],
       [0.32849977, 0.62931547, 0.92167764, 0.88698873, 0.81583856],
       [0.93697486, 0.7748768 , 0.29010674, 0.72361312, 0.95650815],
       [0.97205414, 0.22827648, 0.26450115, 0.95695298, 0.37835904],
       [0.99984543, 0.8668748 , 0.7134479 , 0.95709477, 0.88899746]])

In [22]:
a.shape

(5, 5)

In [23]:
b  = np.random.rand(5,5)
b

array([[0.56382575, 0.73571034, 0.04546502, 0.34637068, 0.02050685],
       [0.99837021, 0.67242514, 0.32658185, 0.36083642, 0.29238539],
       [0.82929129, 0.35797126, 0.24071535, 0.95051037, 0.02487523],
       [0.69299985, 0.86559694, 0.38184922, 0.44934935, 0.68468128],
       [0.74541629, 0.44852026, 0.55797374, 0.50605027, 0.1955412 ]])

In [24]:
a + b

array([[1.29570912, 1.15251239, 0.66509974, 0.65950258, 0.7548149 ],
       [1.32686998, 1.30174061, 1.24825949, 1.24782515, 1.10822395],
       [1.76626615, 1.13284806, 0.53082209, 1.67412349, 0.98138338],
       [1.66505399, 1.09387342, 0.64635038, 1.40630233, 1.06304032],
       [1.74526172, 1.31539506, 1.27142164, 1.46314504, 1.08453866]])

In [25]:
a-b

array([[ 0.16805763, -0.31890829,  0.57416969, -0.03323879,  0.7138012 ],
       [-0.66987045, -0.04310966,  0.59509579,  0.52615231,  0.52345317],
       [ 0.10768357,  0.41690555,  0.0493914 , -0.22689726,  0.93163292],
       [ 0.27905429, -0.63732046, -0.11734807,  0.50760363, -0.30632224],
       [ 0.25442914,  0.41835454,  0.15547416,  0.4510445 ,  0.69345626]])

In [26]:
a*b

array([[0.41265469, 0.30664558, 0.02817171, 0.10845971, 0.01505835],
       [0.32796438, 0.42316754, 0.30100319, 0.32005784, 0.23853928],
       [0.77702509, 0.27738362, 0.06983315, 0.68780177, 0.02379336],
       [0.67363337, 0.19759543, 0.10099956, 0.4300062 , 0.25905535],
       [0.74530107, 0.38881091, 0.39808519, 0.48433806, 0.17383563]])

In [27]:
a/b

array([[ 1.2980666 ,  0.5665301 , 13.62882226,  0.90403694, 35.80793591],
       [ 0.32903602,  0.93588928,  2.82219492,  2.45814636,  2.79028494],
       [ 1.12985012,  2.16463414,  1.20518591,  0.76128903, 38.4522276 ],
       [ 1.40267583,  0.26372145,  0.69268481,  2.12964139,  0.55260609],
       [ 1.34132491,  1.93274391,  1.27864064,  1.89130374,  4.5463434 ]])

In [28]:
np.transpose(a)

array([[0.73188337, 0.32849977, 0.93697486, 0.97205414, 0.99984543],
       [0.41680205, 0.62931547, 0.7748768 , 0.22827648, 0.8668748 ],
       [0.61963472, 0.92167764, 0.29010674, 0.26450115, 0.7134479 ],
       [0.31313189, 0.88698873, 0.72361312, 0.95695298, 0.95709477],
       [0.73430805, 0.81583856, 0.95650815, 0.37835904, 0.88899746]])

In [29]:
1/a

array([[1.36633791, 2.39922043, 1.61385406, 3.19354248, 1.36182628],
       [3.04414221, 1.58902814, 1.08497804, 1.12741004, 1.2257327 ],
       [1.06726449, 1.29052773, 3.44700709, 1.38195394, 1.0454694 ],
       [1.02874928, 4.38065273, 3.78070183, 1.04498342, 2.6429922 ],
       [1.00015459, 1.15356912, 1.40164404, 1.04482861, 1.12486261]])

## PROBLEMAS

1. Escribe una función **suma_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea la suma de las dos matrices originales. No utilices la operación de suma incorporada de NumPy (+).

In [32]:
import numpy as np

def suma_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LA MISMA DIMENSIÓN
  filas, columnas = A.shape
  # Creamoa una matriz resultados vacía
  resultado = np.zeros((filas, columnas))

  # Vamos elemento a elemento sumando las dos matrices
  for i in range(filas):
       for j in range(columnas):
            resultado[i, j] = A[i, j] + B[i, j]
  return resultado

# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
assert np.array_equal(suma_matrices(A, B), np.array([[6, 8], [10, 12]]))

2. Escribe una función **transpuesta** que tome una matriz **NumPy** como argumento y **devuelva su transpuesta**. No utilices la propiedad T de NumPy.

In [1]:
import numpy as np

def transpuesta(A):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
   filas, columnas = A.shape
   transpuestaA = np.zeros((columnas, filas))

   for i in range(filas):
      for j in range(columnas):
          transpuestaA[j, i] = A[i, j]
   return transpuestaA

# Pruebas
A = np.array([[1, 2, 3], [4, 5, 6]])
assert np.array_equal(transpuesta(A), np.array([[1, 4], [2, 5], [3, 6]]))

3. Escribe una función **multiplicar_matrices** que tome dos matrices **NumPy** como argumentos y devuelva una nueva matriz que sea el resultado de la multiplicación de las dos matrices originales. No utilices la operación de multiplicación de matrices incorporada de NumPy (@ o np.dot).

In [9]:
import numpy as np

def multiplicar_matrices(A, B):
  # INTRODUCIR EL CÓDIGO DE LA FUNCIÓN AQUÍ
  # VALIDA QUE LAS MATRICES DE ENTRADA TIENEN LAS DIMENSIONES
  # ADECUADAS QUE PERMITEN LA MULTIPLICACIÓN MATRICIAL

  if A.shape[1] != B.shape[0]:
      raise ValueError("Las matrices no son compatibles para la multiplicación.")

  filas_A, columnas_A = A.shape
  filas_B, columnas_B = B.shape

  # Creamos una matriz vacía para el resultado
  resultado = np.zeros((filas_A, columnas_B), dtype=A.dtype)

  for i in range(filas_A):
      for j in range(columnas_B):
          for k in range(columnas_A):
                resultado[i, j] += A[i, k] * B[k, j]
  return resultado
# Pruebas
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
assert np.array_equal(multiplicar_matrices(A, B), np.array([[4, 4], [10, 8]]))